config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy]
  end

  get 'welcome/index'

  authenticated :user do
    root :to => 'users#show', as: :authenticated_root
  end

  root :to => 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  belongs_to :user

  def time_left
    if self.created_at > (Time.now - 7.days)
      distance_of_time_in_words(self.created_at, (Time.now - 7.days), include_seconds: true)
    else
      "Overdue: " + distance_of_time_in_words(self.created_at, Time.now - 7.days, include_seconds: true)
    end

  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  username               :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_uniqueness_of :username

  has_many :items

  enum role: [:standard, :admin]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    # raise
    @user = current_user
    @item = Item.create
    @item.user = current_user
    @item.assign_attributes(item_params)

    if @item.save
      flash[:notice] = "Your to-do was saved."
      redirect_to user_path @user
    else
      flash[:alert] = "Couldn't save your to-do, please try again."
      redirect_to user_path current_user
    end
  end

  def destroy

    # @user = current_user
    # @item = @user.items.find(params[:id])

    @item = Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "The task was completed and removed."
    else
      flash[:alert] = "Failed to remove the task."
    end

    respond_to do |format|
      format.html
      format.js
    end

  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    if params[:id]
      @user = User.find(params[:id])
      if !policy(@user).show?
      # if @user != current_user
        flash[:error] = "can't view this user's profile"
        redirect_to root_path
      end
    else
      @user = current_user
    end

    @item = Item.new
    @items = @user.items.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [user, item] do |f| %>
  <%= f.text_field :name, placeholder: "Add a to-do!" %>
  <%= f.submit %>
<% end %>

app/views/items/_item.html.erb
<div id=<%="item-#{item.id}"%>>
  <%= link_to "", user_item_path(user, item), method: :delete, class: 'glyphicon glyphicon-ok', remote: true %>
  <%= item.name %>
  <font style= "color: #888888"><small><p><%= item.time_left %> left to complete this.</p></small></font>
</div>

app/views/items/destroy.js.erb
$('#item-' +<%= @item.id %>).hide();
$('#flash').html("<%= escape_javascript(render partial: 'layouts/flash', locals: {flash: flash}) %>");

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:error] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= welcome_index_path %>"><font color= #126B1D>Blocitoff</font></a>
      </div>
        <div class="nav navbar-nav navbar-right">
          <div class="user_block">
            <% if user_signed_in? %>
              Signed in as: <a href="<%= user_path(current_user) %>"><strong><%= current_user.username %></strong></a> |
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
            <% else %>
              <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
              <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div id="flash">
        <%= render "layouts/flash", locals: {flash: flash} %>
      </div>
      
      <%= yield %>
    </div>

</body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="col-md-6">
<h1><%= @user.username.capitalize %>'s Profile</h1>
<p><%= @user.email %></p>
</div>
<div class="container">
  <h4>New To-Do</h4>
  <%= render partial: 'items/form', locals: {user: @user, item: @item} %>
</div>
<br>
<h3>My To-Do List: <small><font style= "color: #126B1D"><%= pluralize(@user.items.count, 'task') %></font> | <%= link_to "Refresh", ""  %></small></h3>
<% @user.items.each do |item| %>
 <%= render partial: 'items/item', locals: {item: item, user: @user} %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>